/*
	ALTER TABLE SERVE PER MODIFICARE UNA TABLE GIA' ESISTENTE
	SENZA DOVERLA RICREARE.
	CON ALTER TABLE:
	AGGIUNGERE COLONNE
	MODIFICARE COLONNE
	ELIMINARE COLONNE
	AGGIUNGERE VINCOLI (PK/FK/UNIQUE/CHECK)
	ELIMINARE VINCOLI
	RINOMINARE COLONNE
	CAMBIARE I TIPI DI DATI
	MODIFICARE UNA COLONNA IN DEFAULT
*/

-- AGGIUNGERE UNA COLONNA A STUDENTI

ALTER TABLE Studenti
ADD Indirizzo NVARCHAR(150) NULL;

-- MODIFICARE TIPO DI DATO DA NVARCHAR(50) A VARCHAR(20)

ALTER TABLE Studenti
ALTER COLUMN Telefono VARCHAR(100) NOT NULL;

-- RINOMINARE UNA COLONNA

EXEC sp_rename 'Studenti.DataNascita', 'Data_di_Nascita'

-- ELIMINARE UNA COLONNA

ALTER TABLE Studenti
DROP COLUMN Indirizzo;

-- AGGIUNGERE UNA FOREING KEY

ALTER TABLE Voti
ADD CONSTRAINT FK_Voti_Studenti
FOREIGN KEY (StudentiID) REFERENCES Studenti(StudentiID) 

-- ELIMINARE UNA FOREIGN KEY

ALTER TABLE Voti
DROP CONSTRAINT FK_Voti_Studenti;

-- AGGIUNGERE VINCOLO UNIQUE

ALTER TABLE Studenti
ADD CONSTRAINT UQ_Studenti_Telefono UNIQUE(Telefono);

-- AGGIUNGERE UN VALORE DEFAULT
-- IMPOSTARE 'SUPERATO' = 1 | 'NON SUPERATO' = 0

ALTER TABLE Voti
ADD CONSTRAINT DF_Voti_Superati DEFAULT 1 FOR Superato; 